### ISSUE TITLE
Cannot find or setup any route name for log viewer

### ISSUE THREAD

**Issue by marsender** [frankdekker/symfony-log-viewer-bundle#197]
Log viewer is working fine with this routes config config/routes/fd_log_viewer.yaml :
```
fd_symfony_log_viewer:
    resource: .
    type: fd_symfony_log_viewer
    prefix: /log-viewer
```
however, the route name fd_symfony_log_viewer is not available.
For example, this twig path does not work :
`{{ path('fd_symfony_log_viewer') }}`

How to setup a route name ?
